### ISSUE TITLE
Fatrat doesn't start in Ubuntu

### ISSUE THREAD

**Issue by simpledev1** [LubosD/fatrat#46]
Fatrat Version: 1.2.0
Ubuntu 18.04
```
:~$ fatrat
Current locale "en"
Loading queues
Transfer::createInstance(): "GeneralDownload"
Transfer::createInstance(): "GeneralDownload"
Transfer::createInstance(): "GeneralDownload"
Transfer::createInstance(): "GeneralDownload"
Transfer::createInstance(): "GeneralDownload"
Transfer::createInstance(): "GeneralDownload"
Transfer::createInstance(): "GeneralDownload"
Transfer::createInstance(): "GeneralDownload"
Transfer::createInstance(): "GeneralDownload"
Transfer::createInstance(): "GeneralDownload"
Transfer::createInstance(): "GeneralDownload"
Transfer::createInstance(): "GeneralDownload"
Transfer::createInstance(): "GeneralDownload"
Transfer::createInstance(): "GeneralDownload"
Transfer::createInstance(): "GeneralDownload"
Transfer::createInstance(): "GeneralDownload"
Transfer::createInstance(): "GeneralDownload"
Transfer::createInstance(): "GeneralDownload"
Transfer::createInstance(): "GeneralDownload"
Transfer::createInstance(): "GeneralDownload"
CurlDownload(0x55c7ec8cbd20) changeActive true
Adding a polling master 21 QThread(0x55c7ec6918e0)
The limit is 0
----------- CurlDownload::startSegment(): 0
Start new seg:  0 419112667
CurlDownload::startSegment(): seg offset: 0 ; bytes: 419112667
CurlDownload(0x55c7ec8cbd20) changeActive false
Before final simplify segments: ()
After final simplify segments: ()
----------- CurlDownload::startSegment(): 0
Segmentation fault (core dumped)

```

**Comment by LubosD** [comment]
Sorry, but I can't act on this without a backtrace. Please do this:

```
gdb fatrat
run
(wait until it crashes)
bt
```

**Comment by simpledev1** [comment]
Here's the backtrace
```
gdb fatrat
GNU gdb (Ubuntu 8.1-0ubuntu3) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from fatrat...(no debugging symbols found)...done.
(gdb) fatrat
Undefined command: "fatrat".  Try "help".
(gdb) run
Starting program: /usr/bin/fatrat 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe5840700 (LWP 14350)]
[New Thread 0x7fffdb7bb700 (LWP 14351)]
[New Thread 0x7fffdafba700 (LWP 14352)]
[New Thread 0x7fffd90e2700 (LWP 14354)]
Current locale "en"
[New Thread 0x7fffd88e1700 (LWP 14356)]
Loading queues
Transfer::createInstance(): "GeneralDownload"
Transfer::createInstance(): "GeneralDownload"
Transfer::createInstance(): "GeneralDownload"
Transfer::createInstance(): "GeneralDownload"
Transfer::createInstance(): "GeneralDownload"
Transfer::createInstance(): "GeneralDownload"
Transfer::createInstance(): "GeneralDownload"
Transfer::createInstance(): "GeneralDownload"
Transfer::createInstance(): "GeneralDownload"
Transfer::createInstance(): "GeneralDownload"
Transfer::createInstance(): "GeneralDownload"
Transfer::createInstance(): "GeneralDownload"
Transfer::createInstance(): "GeneralDownload"
Transfer::createInstance(): "GeneralDownload"
Transfer::createInstance(): "GeneralDownload"
Transfer::createInstance(): "GeneralDownload"
Transfer::createInstance(): "GeneralDownload"
Transfer::createInstance(): "GeneralDownload"
Transfer::createInstance(): "GeneralDownload"
Transfer::createInstance(): "GeneralDownload"
CurlDownload(0x555555b87200) changeActive true
Adding a polling master 21 QThread(0x5555559a48c0)
The limit is 0
----------- CurlDownload::startSegment(): 0
Start new seg:  0 419112667
CurlDownload::startSegment(): seg offset: 0 ; bytes: 419112667
CurlDownload(0x555555b87200) changeActive false
Before final simplify segments: ()
After final simplify segments: ()
----------- CurlDownload::startSegment(): 0

Thread 1 "fatrat" received signal SIGSEGV, Segmentation fault.
0x0000555555664eb0 in UrlClient::progress() const ()
(gdb) bt
#0  0x0000555555664eb0 in UrlClient::progress() const ()
#1  0x0000555555655c5c in CurlDownload::updateSegmentProgress() ()
#2  0x0000555555655ee3 in CurlDownload::startSegment(int) ()
#3  0x0000555555657d43 in CurlDownload::changeActive(bool) ()
#4  0x00005555556169c2 in Transfer::setState(Transfer::State) ()
#5  0x0000555555614deb in Transfer::load(QDomNode const&) ()
#6  0x00005555556556b5 in CurlDownload::load(QDomNode const&) ()
#7  0x00005555555f7c2e in Queue::loadQueue(QDomNode const&) ()
#8  0x00005555555fa6eb in Queue::loadQueues() ()
#9  0x00005555555c968a in main ()
(gdb) 

```

**Comment by simpledev1** [comment]
Nevermind. I deleted all configuration files, updated all my system packages and reinstalled fatrat and now it works perfectly!
